from Analyzer.utils.Pipeline import Pipeline
from Analyzer.utils.post import mask_processing
from Analyzer.utils.unify_path import unify_path
from Analyzer.utils.mask_generation import calculate_wat_mask,calculate_pwat_mask,calculate_wat_segmentation_sWAT,calculate_wat_segmentation_pWAT